#!/usr/bin/env bash
#Rick-roll-redirect

sudo sed -i "0,/location \/ {/s//location \/redirect_me {\n\t\treturn 301 \$scheme:\/\/https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation \/ {/" /etc/nginx/sites-available/default

sudo service nginx restart
