#!/usr/bin/env bash
# installing HAproxy about things

sudo apt-get -y update
sudo apt-get -y ugrade

sudo apt-get -y install haproxy
sudo service haproxy start

FrontendConfig="\nfrontend http_web\n\
\tbind *:80\n\
\tstats uri /haproxy?stats\n\
\tdefault_backend custom_backend\n"

BackendConfig="\nbackend custom_backend\n\
\tbalance roundrobin\n\
\t\tserver web-01 54.152.238.19:80 check\n\
\t\tserver web-02 52.91.219.116:80 check"

sudo echo -e ${FrontendConfig} | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo -e ${BackendConfig} | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
